# Generated by Django 4.2 on 2024-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0002_alter_department_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
