# Generated by Django 4.2 on 2024-03-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0004_anchorpoint_building_coordinationgraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnchorPoint',
        ),
    ]
