# Generated by Django 4.2 on 2024-03-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0006_anchorpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anchorpoint',
            old_name='latitude',
            new_name='anchor_coords',
        ),
        migrations.RemoveField(
            model_name='anchorpoint',
            name='longitude',
        ),
    ]
