# Generated by Django 4.2 on 2024-03-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0007_rename_latitude_anchorpoint_anchor_coords_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnchorPoint',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='CoordinationGraph',
        ),
    ]
