# Generated by Django 4.2 on 2024-03-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0008_delete_anchorpoint_delete_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_coords', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=100)),
                ('prop_type', models.CharField(max_length=100)),
                ('prop_coord', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinationGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_node', models.DecimalField(decimal_places=9, max_digits=20)),
                ('current_node', models.DecimalField(decimal_places=9, max_digits=20)),
                ('next_node', models.DecimalField(decimal_places=9, max_digits=20)),
                ('is_dest', models.BooleanField(default=False)),
            ],
        ),
    ]
