# Generated by Django 4.2 on 2024-03-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0009_anchorpoint_building_coordinationgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorpoint',
            name='anchor_coords',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='prop_coord',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinationgraph',
            name='current_node',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinationgraph',
            name='next_node',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinationgraph',
            name='prev_node',
            field=models.CharField(max_length=100),
        ),
    ]
